service:
  name: example

plugins:
  - serverless-webpack
  - serverless-step-functions
  - serverless-offline-step-functions
  - serverless-offline

custom:
  serverless-offline-step-functions:
    port: 8014

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage}

functions:
  helloWorld:
    handler: src/handler.helloWorld

stepFunctions:
  stateMachines:
    HelloWorld:
      events:
        - http:
            path: hello
            method: GET
      name: HelloWorld
      definition:
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource:
              Fn::GetAtt: [helloWorld, Arn]
            End: true
